# https://jekyllrb.com/docs/configuration/

# site-wide variables
title: ARTE Lab
email: tongzhang@ucas.ac.cn
description: ARTE Lab at UCAS (LAMP): Autonomous Representation of Temps and Espace, with research in world models, spatial intelligence, and autonomous driving.
url: "https://arte-lab.github.io"
#google: Rob Patro # default name to search on Google Scholar
github: https://arte-lab.github.io
#twitter: nomad421 # default Twitter handle, without the @
#instagram: fakeinstagramhandle # default Instagram handle, without the @
#youtube: fakeyoutubechannel # default YouTube channel handle

# base directory where site is hosted
# set to "" if hosting at a custom domain, eg yoursite.com
baseurl: "/"

collections:
  members:
    output: true
  projects:
    output: true
    permalink: /research/:name/

defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      description: ARTE Lab at UCAS (LAMP): Autonomous Representation of Temps and Espace, with research in world models, spatial intelligence, and autonomous driving. # description that will show under search engine results
      background: images/test-tube.jpg # background image in header and footer
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /newsposts
  - scope:
      path: "newsposts"
    values:
      layout: post
  - scope:
      path: "assets/cv"
    values:
      layout: default
  - scope:
      type: "projects"
    values:
      layout: project
      background: images/space.jpg

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
